/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `SavingsAccount`;

DROP TABLE IF EXISTS `CurrentAccount`;

DROP TABLE IF EXISTS `Account`;

CREATE TABLE `Account` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `id_customer` BIGINT NOT NULL,
  `id_employee` BIGINT NOT NULL,
  `balance` DOUBLE NOT NULL,
  `creationDate` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `CurrentAccount` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `overdraft` DOUBLE NOT NULL,
  CONSTRAINT `CurrentAccount_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `SavingsAccount` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `rate` DOUBLE NOT NULL,
  CONSTRAINT `SavingsAccount_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `Account`
  ADD CONSTRAINT `Account_id_customer_fk`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Customer` (`id`),
  ADD CONSTRAINT `Account_id_employee_fk`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Employee` (`id`)
*/

