SET FOREIGN_KEY_CHECKS = 0;

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `SavingsAccount`;

DROP TABLE IF EXISTS `CurrentAccount`;

DROP TABLE IF EXISTS `Account`;

CREATE TABLE `Account` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `id_customer` BIGINT NOT NULL,
  `id_employee` BIGINT NOT NULL,
  `balance` DOUBLE NOT NULL,
  `creationDate` VARCHAR(512) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `CurrentAccount` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `overdraft` DOUBLE NOT NULL,
  CONSTRAINT `CurrentAccount_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `SavingsAccount` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `rate` DOUBLE NOT NULL,
  CONSTRAINT `SavingsAccount_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Account` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `Account`
  ADD CONSTRAINT `Account_id_customer_fk`
    FOREIGN KEY (`id_customer`)
    REFERENCES `Customer` (`id`),
  ADD CONSTRAINT `Account_id_employee_fk`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Employee` (`id`)
*/

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Virement`;

DROP TABLE IF EXISTS `Operation`;

DROP TABLE IF EXISTS `BaseOperation`;

CREATE TABLE `BaseOperation` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `id_account` BIGINT NOT NULL,
  `id_employee` BIGINT NOT NULL,
  `date` VARCHAR(255) NOT NULL,
  `montant` DOUBLE NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Operation` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `typeOperation` INT NOT NULL,
  CONSTRAINT `Operation_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `BaseOperation` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Virement` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `id_account` BIGINT NULL,
  CONSTRAINT `Virement_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `BaseOperation` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `BaseOperation`
  ADD CONSTRAINT `BaseOperation_id_account_fk`
    FOREIGN KEY (`id_account`)
    REFERENCES `Account` (`id`),
  ADD CONSTRAINT `BaseOperation_id_employee_fk`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Employee` (`id`)
*/

/*
ALTER TABLE `Virement`
  ADD CONSTRAINT `Virement_id_account_fk`
    FOREIGN KEY (`id_account`)
    REFERENCES `Account` (`id`)
*/

/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `ReloadSession`;

DROP TABLE IF EXISTS `Session`;

DROP TABLE IF EXISTS `Token`;

DROP TABLE IF EXISTS `Group_members`;

DROP TABLE IF EXISTS `Group`;

DROP TABLE IF EXISTS `Employee_subordinate`;

DROP TABLE IF EXISTS `Employee`;

DROP TABLE IF EXISTS `Customer`;

DROP TABLE IF EXISTS `Person`;

CREATE TABLE `Person` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `name` VARCHAR(512) NOT NULL,
  `surname` VARCHAR(512) NOT NULL,
  `email` VARCHAR(512) NOT NULL,
  `passwd` VARCHAR(2048) NOT NULL,
  `id_token` INT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `email_i`
  ON `Person` (`email`);

CREATE TABLE `Customer` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  CONSTRAINT `Customer_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Person` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Employee` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  CONSTRAINT `Employee_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Person` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Employee_subordinate` (
  `object_id` BIGINT NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT NULL,
  CONSTRAINT `Employee_subordinate_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Employee` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Employee_subordinate_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Employee` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Employee_subordinate` (`object_id`);

CREATE INDEX `index_i`
  ON `Employee_subordinate` (`index`);

CREATE TABLE `Group` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Group_members` (
  `object_id` BIGINT NOT NULL,
  `value` BIGINT NULL,
  CONSTRAINT `Group_members_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Group_members_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Employee` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Group_members` (`object_id`);

CREATE TABLE `Token` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `id_person` INT NULL,
  `token` VARCHAR(1024) NOT NULL
  /*
  CONSTRAINT `Token_id_person_fk`
    FOREIGN KEY (`id_person`)
    REFERENCES `Person` (`id`)
  */)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `token_i`
  ON `Token` (`token`);

CREATE TABLE `Session` (
  `id` INT NOT NULL PRIMARY KEY,
  `begin` BIGINT UNSIGNED NOT NULL,
  `end` BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `Session_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Token` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `ReloadSession` (
  `id` INT NOT NULL PRIMARY KEY,
  `reloaded` TINYINT(1) NOT NULL,
  CONSTRAINT `ReloadSession_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Token` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `Person`
  ADD CONSTRAINT `Person_id_token_fk`
    FOREIGN KEY (`id_token`)
    REFERENCES `Token` (`id`)
*/

SET FOREIGN_KEY_CHECKS = 1;