/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
 DROP TABLE IF EXISTS `News`;

 CREATE TABLE `News` (
   `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   `title` VARCHAR(127) NOT NULL,
   `date` VARCHAR(127) NOT NULL,
   `text` TEXT NOT NULL
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
