/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Virement`;

DROP TABLE IF EXISTS `Operation`;

DROP TABLE IF EXISTS `BaseOperation`;

CREATE TABLE `BaseOperation` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `id_account` BIGINT NOT NULL,
  `id_employee` BIGINT NOT NULL,
  `date` VARCHAR(255) NOT NULL,
  `montant` DOUBLE NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Operation` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `typeOperation` INT NOT NULL,
  CONSTRAINT `Operation_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `BaseOperation` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Virement` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  `id_account` BIGINT NULL,
  CONSTRAINT `Virement_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `BaseOperation` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

/*
ALTER TABLE `BaseOperation`
  ADD CONSTRAINT `BaseOperation_id_account_fk`
    FOREIGN KEY (`id_account`)
    REFERENCES `Account` (`id`),
  ADD CONSTRAINT `BaseOperation_id_employee_fk`
    FOREIGN KEY (`id_employee`)
    REFERENCES `Employee` (`id`)
*/

/*
ALTER TABLE `Virement`
  ADD CONSTRAINT `Virement_id_account_fk`
    FOREIGN KEY (`id_account`)
    REFERENCES `Account` (`id`)
*/

