/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Group_members`;

DROP TABLE IF EXISTS `Group`;

DROP TABLE IF EXISTS `Employee_subordinate`;

DROP TABLE IF EXISTS `Employee`;

DROP TABLE IF EXISTS `Customer`;

DROP TABLE IF EXISTS `Person`;

CREATE TABLE `Person` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Customer` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  CONSTRAINT `Customer_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Person` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Employee` (
  `id` BIGINT NOT NULL PRIMARY KEY,
  CONSTRAINT `Employee_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Person` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `Employee_subordinate` (
  `object_id` BIGINT NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT NULL,
  CONSTRAINT `Employee_subordinate_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Employee` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Employee_subordinate_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Employee` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Employee_subordinate` (`object_id`);

CREATE INDEX `index_i`
  ON `Employee_subordinate` (`index`);

CREATE TABLE `Group` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Group_members` (
  `object_id` BIGINT NOT NULL,
  `value` BIGINT NULL,
  CONSTRAINT `Group_members_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Group_members_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Employee` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Group_members` (`object_id`);

