// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ACCOUNT_ODB_HXX
#define ACCOUNT_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "Account.hpp"

#include "Operation-odb.hxx"
#include "Persons-odb.hxx"

#include <memory>
#include <cstddef>
#include <string>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/polymorphic-info.hxx>
#include <odb/result.hxx>
#include <odb/polymorphic-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Account
  //
  template <>
  struct class_traits< ::Entity::Account >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Entity::Account >
  {
    public:
    typedef ::Entity::Account object_type;
    typedef ::std::shared_ptr< ::Entity::Account > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = true;

    typedef ::Entity::Account root_type;
    typedef ::std::string discriminator_type;
    typedef polymorphic_map<object_type> map_type;
    typedef polymorphic_concrete_info<object_type> info_type;

    static const std::size_t depth = 1UL;

    typedef long int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // CurrentAccount
  //
  template <>
  struct class_traits< ::Entity::CurrentAccount >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Entity::CurrentAccount >
  {
    public:
    typedef ::Entity::CurrentAccount object_type;
    typedef ::std::shared_ptr< ::Entity::CurrentAccount > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = true;

    typedef ::Entity::Account root_type;
    typedef ::Entity::Account base_type;
    typedef object_traits<root_type>::discriminator_type discriminator_type;
    typedef polymorphic_concrete_info<root_type> info_type;

    static const std::size_t depth = 2UL;

    typedef object_traits< ::Entity::Account >::id_type id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      object_traits<root_type>::pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      root_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // SavingsAccount
  //
  template <>
  struct class_traits< ::Entity::SavingsAccount >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Entity::SavingsAccount >
  {
    public:
    typedef ::Entity::SavingsAccount object_type;
    typedef ::std::shared_ptr< ::Entity::SavingsAccount > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = true;

    typedef ::Entity::Account root_type;
    typedef ::Entity::Account base_type;
    typedef object_traits<root_type>::discriminator_type discriminator_type;
    typedef polymorphic_concrete_info<root_type> info_type;

    static const std::size_t depth = 2UL;

    typedef object_traits< ::Entity::Account >::id_type id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      object_traits<root_type>::pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      root_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Account
  //
  template <typename A>
  struct pointer_query_columns< ::Entity::Account, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // typeid_
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    typeid__type_;

    static const typeid__type_ typeid_;

    // t_customer
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    t_customer_type_;

    static const t_customer_type_ t_customer;

    // t_employee
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    t_employee_type_;

    static const t_employee_type_ t_employee;

    // balance
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    balance_type_;

    static const balance_type_ balance;

    // creationDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    creationDate_type_;

    static const creationDate_type_ creationDate;
  };

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::id_type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::typeid__type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  typeid_ (A::table_name, "`typeid`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::t_customer_type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  t_customer (A::table_name, "`id_customer`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::t_employee_type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  t_employee (A::table_name, "`id_employee`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::balance_type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  balance (A::table_name, "`balance`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::Account, id_mysql, A >::creationDate_type_
  pointer_query_columns< ::Entity::Account, id_mysql, A >::
  creationDate (A::table_name, "`creationDate`", 0);

  template <>
  class access::object_traits_impl< ::Entity::Account, id_mysql >:
    public access::object_traits< ::Entity::Account >
  {
    public:
    typedef polymorphic_entry<object_type, id_mysql> entry_type;
    typedef object_traits_impl<root_type, id_mysql> root_traits;

    struct discriminator_image_type
    {
      details::buffer discriminator_value;
      unsigned long discriminator_size;
      my_bool discriminator_null;

      std::size_t version;
    };

    struct id_image_type
    {
      long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    static map_type* map;
    static const info_type info;

    struct image_type
    {
      // id
      //
      long long id_value;
      my_bool id_null;

      // typeid_
      //
      details::buffer typeid_value;
      unsigned long typeid_size;
      my_bool typeid_null;

      // t_customer
      //
      long long t_customer_value;
      my_bool t_customer_null;

      // t_employee
      //
      long long t_employee_value;
      my_bool t_employee_null;

      // balance
      //
      double balance_value;
      my_bool balance_null;

      // creationDate
      //
      details::buffer creationDate_value;
      unsigned long creationDate_size;
      my_bool creationDate_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // operations
    //
    struct operations_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::shared_ptr< ::Entity::BaseOperation > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef mysql::container_statements< operations_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        long long value_value;
        my_bool value_null;

        std::size_t version;
      };

      static void
      bind (MYSQL_BIND*,
            const MYSQL_BIND* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            my_bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    struct t_customer_tag;
    struct t_employee_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static discriminator_type
    discriminator (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef
    mysql::polymorphic_root_object_statements<object_type>
    statements_type;

    typedef statements_type root_statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 1UL;
    static const std::size_t managed_optimistic_column_count = 0UL;
    static const std::size_t discriminator_column_count = 1UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char find_discriminator_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&, bool top = true, bool dyn = true);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&, bool dyn = true);

    static bool
    reload (database&, object_type&, bool dyn = true);

    static void
    update (database&, const object_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const id_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const object_type&, bool top = true, bool dyn = true);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);

    static void
    discriminator_ (statements_type&,
                    const id_type&,
                    discriminator_type*);
  };

  template <>
  class access::object_traits_impl< ::Entity::Account, id_common >:
    public access::object_traits_impl< ::Entity::Account, id_mysql >
  {
  };

  // CurrentAccount
  //
  template <typename A>
  struct pointer_query_columns< ::Entity::CurrentAccount, id_mysql, A >:
    pointer_query_columns< ::Entity::Account, id_mysql, typename A::base_traits >
  {
    // Account
    //
    typedef pointer_query_columns< ::Entity::Account, id_mysql, typename A::base_traits > Account;

    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // overdraft
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    overdraft_type_;

    static const overdraft_type_ overdraft;
  };

  template <typename A>
  const typename pointer_query_columns< ::Entity::CurrentAccount, id_mysql, A >::id_type_
  pointer_query_columns< ::Entity::CurrentAccount, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::CurrentAccount, id_mysql, A >::overdraft_type_
  pointer_query_columns< ::Entity::CurrentAccount, id_mysql, A >::
  overdraft (A::table_name, "`overdraft`", 0);

  template <>
  class access::object_traits_impl< ::Entity::CurrentAccount, id_mysql >:
    public access::object_traits< ::Entity::CurrentAccount >
  {
    public:
    typedef polymorphic_entry<object_type, id_mysql> entry_type;
    typedef object_traits_impl<root_type, id_mysql> root_traits;
    typedef object_traits_impl<base_type, id_mysql> base_traits;

    typedef root_traits::id_image_type id_image_type;

    static const info_type info;

    struct image_type
    {
      base_traits::image_type* base;

      // id
      //
      long long id_value;
      my_bool id_null;

      // overdraft
      //
      double overdraft_value;
      my_bool overdraft_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static bool
    grow (image_type&,
          my_bool*,
          std::size_t = depth);

    static void
    bind (MYSQL_BIND*,
          const MYSQL_BIND* id,
          std::size_t id_size,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*,
          std::size_t = depth);

    static void
    init (id_image_type&, const id_type&);

    static bool
    check_version (const std::size_t*, const image_type&);

    static void
    update_version (std::size_t*, const image_type&, mysql::binding*);

    typedef
    mysql::polymorphic_derived_object_statements<object_type>
    statements_type;

    typedef
    mysql::polymorphic_root_object_statements<root_type>
    root_statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char* const find_statements[depth];
    static const std::size_t find_column_counts[depth];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&, bool top = true, bool dyn = true);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&, bool dyn = true);

    static bool
    reload (database&, object_type&, bool dyn = true);

    static void
    update (database&, const object_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const id_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const object_type&, bool top = true, bool dyn = true);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*,
           std::size_t = depth);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload,
           std::size_t = depth);

    static void
    load_ (database&, root_type&, std::size_t);
  };

  template <>
  class access::object_traits_impl< ::Entity::CurrentAccount, id_common >:
    public access::object_traits_impl< ::Entity::CurrentAccount, id_mysql >
  {
  };

  // SavingsAccount
  //
  template <typename A>
  struct pointer_query_columns< ::Entity::SavingsAccount, id_mysql, A >:
    pointer_query_columns< ::Entity::Account, id_mysql, typename A::base_traits >
  {
    // Account
    //
    typedef pointer_query_columns< ::Entity::Account, id_mysql, typename A::base_traits > Account;

    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // rate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    rate_type_;

    static const rate_type_ rate;
  };

  template <typename A>
  const typename pointer_query_columns< ::Entity::SavingsAccount, id_mysql, A >::id_type_
  pointer_query_columns< ::Entity::SavingsAccount, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Entity::SavingsAccount, id_mysql, A >::rate_type_
  pointer_query_columns< ::Entity::SavingsAccount, id_mysql, A >::
  rate (A::table_name, "`rate`", 0);

  template <>
  class access::object_traits_impl< ::Entity::SavingsAccount, id_mysql >:
    public access::object_traits< ::Entity::SavingsAccount >
  {
    public:
    typedef polymorphic_entry<object_type, id_mysql> entry_type;
    typedef object_traits_impl<root_type, id_mysql> root_traits;
    typedef object_traits_impl<base_type, id_mysql> base_traits;

    typedef root_traits::id_image_type id_image_type;

    static const info_type info;

    struct image_type
    {
      base_traits::image_type* base;

      // id
      //
      long long id_value;
      my_bool id_null;

      // rate
      //
      double rate_value;
      my_bool rate_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static bool
    grow (image_type&,
          my_bool*,
          std::size_t = depth);

    static void
    bind (MYSQL_BIND*,
          const MYSQL_BIND* id,
          std::size_t id_size,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*,
          std::size_t = depth);

    static void
    init (id_image_type&, const id_type&);

    static bool
    check_version (const std::size_t*, const image_type&);

    static void
    update_version (std::size_t*, const image_type&, mysql::binding*);

    typedef
    mysql::polymorphic_derived_object_statements<object_type>
    statements_type;

    typedef
    mysql::polymorphic_root_object_statements<root_type>
    root_statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char* const find_statements[depth];
    static const std::size_t find_column_counts[depth];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&, bool top = true, bool dyn = true);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&, bool dyn = true);

    static bool
    reload (database&, object_type&, bool dyn = true);

    static void
    update (database&, const object_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const id_type&, bool top = true, bool dyn = true);

    static void
    erase (database&, const object_type&, bool top = true, bool dyn = true);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*,
           std::size_t = depth);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload,
           std::size_t = depth);

    static void
    load_ (database&, root_type&, std::size_t);
  };

  template <>
  class access::object_traits_impl< ::Entity::SavingsAccount, id_common >:
    public access::object_traits_impl< ::Entity::SavingsAccount, id_mysql >
  {
  };

  // Account
  //
  template <>
  struct alias_traits<
    ::Entity::Person,
    id_mysql,
    access::object_traits_impl< ::Entity::Account, id_mysql >::t_customer_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Entity::Customer,
    id_mysql,
    access::object_traits_impl< ::Entity::Account, id_mysql >::t_customer_tag>
  {
    typedef alias_traits<
      ::Entity::Person,
      id_mysql,
      access::object_traits_impl< ::Entity::Account, id_mysql >::t_customer_tag>
    base_traits;

    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Entity::Person,
    id_mysql,
    access::object_traits_impl< ::Entity::Account, id_mysql >::t_employee_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::Entity::Employee,
    id_mysql,
    access::object_traits_impl< ::Entity::Account, id_mysql >::t_employee_tag>
  {
    typedef alias_traits<
      ::Entity::Person,
      id_mysql,
      access::object_traits_impl< ::Entity::Account, id_mysql >::t_employee_tag>
    base_traits;

    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Entity::Account, id_mysql >
  {
    // t_customer
    //
    typedef
    odb::alias_traits<
      ::Entity::Customer,
      id_mysql,
      access::object_traits_impl< ::Entity::Account, id_mysql >::t_customer_tag>
    t_customer_alias_;

    // t_employee
    //
    typedef
    odb::alias_traits<
      ::Entity::Employee,
      id_mysql,
      access::object_traits_impl< ::Entity::Account, id_mysql >::t_employee_tag>
    t_employee_alias_;
  };

  template <typename A>
  struct query_columns< ::Entity::Account, id_mysql, A >:
    query_columns_base< ::Entity::Account, id_mysql >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // typeid_
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    typeid__type_;

    static const typeid__type_ typeid_;

    // t_customer
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    t_customer_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Entity::Customer,
        id_mysql,
        t_customer_alias_ > >
    t_customer_pointer_type_;

    struct t_customer_type_: t_customer_pointer_type_, t_customer_column_type_
    {
      t_customer_type_ (const char* t, const char* c, const char* conv)
        : t_customer_column_type_ (t, c, conv)
      {
      }
    };

    static const t_customer_type_ t_customer;

    // t_employee
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    t_employee_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::Entity::Employee,
        id_mysql,
        t_employee_alias_ > >
    t_employee_pointer_type_;

    struct t_employee_type_: t_employee_pointer_type_, t_employee_column_type_
    {
      t_employee_type_ (const char* t, const char* c, const char* conv)
        : t_employee_column_type_ (t, c, conv)
      {
      }
    };

    static const t_employee_type_ t_employee;

    // balance
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    balance_type_;

    static const balance_type_ balance;

    // creationDate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    creationDate_type_;

    static const creationDate_type_ creationDate;
  };

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::id_type_
  query_columns< ::Entity::Account, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::typeid__type_
  query_columns< ::Entity::Account, id_mysql, A >::
  typeid_ (A::table_name, "`typeid`", 0);

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::t_customer_type_
  query_columns< ::Entity::Account, id_mysql, A >::
  t_customer (A::table_name, "`id_customer`", 0);

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::t_employee_type_
  query_columns< ::Entity::Account, id_mysql, A >::
  t_employee (A::table_name, "`id_employee`", 0);

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::balance_type_
  query_columns< ::Entity::Account, id_mysql, A >::
  balance (A::table_name, "`balance`", 0);

  template <typename A>
  const typename query_columns< ::Entity::Account, id_mysql, A >::creationDate_type_
  query_columns< ::Entity::Account, id_mysql, A >::
  creationDate (A::table_name, "`creationDate`", 0);

  // CurrentAccount
  //
  template <typename A>
  struct query_columns< ::Entity::CurrentAccount, id_mysql, A >:
    query_columns< ::Entity::Account, id_mysql, typename A::base_traits >
  {
    // Account
    //
    typedef query_columns< ::Entity::Account, id_mysql, typename A::base_traits > Account;

    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // overdraft
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    overdraft_type_;

    static const overdraft_type_ overdraft;
  };

  template <typename A>
  const typename query_columns< ::Entity::CurrentAccount, id_mysql, A >::id_type_
  query_columns< ::Entity::CurrentAccount, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::Entity::CurrentAccount, id_mysql, A >::overdraft_type_
  query_columns< ::Entity::CurrentAccount, id_mysql, A >::
  overdraft (A::table_name, "`overdraft`", 0);

  // SavingsAccount
  //
  template <typename A>
  struct query_columns< ::Entity::SavingsAccount, id_mysql, A >:
    query_columns< ::Entity::Account, id_mysql, typename A::base_traits >
  {
    // Account
    //
    typedef query_columns< ::Entity::Account, id_mysql, typename A::base_traits > Account;

    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // rate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        double,
        mysql::id_double >::query_type,
      mysql::id_double >
    rate_type_;

    static const rate_type_ rate;
  };

  template <typename A>
  const typename query_columns< ::Entity::SavingsAccount, id_mysql, A >::id_type_
  query_columns< ::Entity::SavingsAccount, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::Entity::SavingsAccount, id_mysql, A >::rate_type_
  query_columns< ::Entity::SavingsAccount, id_mysql, A >::
  rate (A::table_name, "`rate`", 0);
}

#include "Account-odb.ixx"

#include <odb/post.hxx>

#endif // ACCOUNT_ODB_HXX
