// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef NEWS_ODB_HXX
#define NEWS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "News.hpp"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // News
  //
  template <>
  struct class_traits< ::Entity::News >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Entity::News >
  {
    public:
    typedef ::Entity::News object_type;
    typedef ::std::shared_ptr< ::Entity::News > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // News
  //
  template <typename A>
  struct query_columns< ::Entity::News, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    id_type_;

    static const id_type_ id;

    // title
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    title_type_;

    static const title_type_ title;

    // date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    date_type_;

    static const date_type_ date;

    // text
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    text_type_;

    static const text_type_ text;
  };

  template <typename A>
  const typename query_columns< ::Entity::News, id_mysql, A >::id_type_
  query_columns< ::Entity::News, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::Entity::News, id_mysql, A >::title_type_
  query_columns< ::Entity::News, id_mysql, A >::
  title (A::table_name, "`title`", 0);

  template <typename A>
  const typename query_columns< ::Entity::News, id_mysql, A >::date_type_
  query_columns< ::Entity::News, id_mysql, A >::
  date (A::table_name, "`date`", 0);

  template <typename A>
  const typename query_columns< ::Entity::News, id_mysql, A >::text_type_
  query_columns< ::Entity::News, id_mysql, A >::
  text (A::table_name, "`text`", 0);

  template <typename A>
  struct pointer_query_columns< ::Entity::News, id_mysql, A >:
    query_columns< ::Entity::News, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::Entity::News, id_mysql >:
    public access::object_traits< ::Entity::News >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_id
      //
      long long m_id_value;
      my_bool m_id_null;

      // m_title
      //
      details::buffer m_title_value;
      unsigned long m_title_size;
      my_bool m_title_null;

      // m_date
      //
      details::buffer m_date_value;
      unsigned long m_date_size;
      my_bool m_date_null;

      // m_text
      //
      details::buffer m_text_value;
      unsigned long m_text_size;
      my_bool m_text_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Entity::News, id_common >:
    public access::object_traits_impl< ::Entity::News, id_mysql >
  {
  };

  // News
  //
}

#include "News-odb.ixx"

#include <odb/post.hxx>

#endif // NEWS_ODB_HXX
